### ISSUE TITLE
A question about dataloader for test 

### ISSUE THREAD

**Issue by rickyang1114** [Albert0147/LPA_SFDA#6]
Hi, there!

I notice that in the dataloader for test, the parameter `shuffle` of the init of DataLoader is set to `False` in Visda17, whereas in office-home and office31, it is set to `True`. Is this setting on purpose?

i.e. in line 120 of `tar_adaptation.py`, line 154 of `office-home/train_tar.py`, line 197 of `office-home/office31_tar.py`

**Comment by Albert0147** [comment]
Hi, for testing it does not matter to set it to true or false, basically most of the codes are based on SHOT.

**Comment by rickyang1114** [comment]
Thanks for your reply
