### ISSUE TITLE
Experimental setting for Source-free  paritial-set DA

### ISSUE THREAD

**Issue by shaojiezhanglalala** [Albert0147/LPA_SFDA#7]
Hi, professor. I'm very interesting in your paper. Could you provide the **Office-Home** experiment setting file in **paritial-set DA** settings, i.e., hyper-parameters _K_ and _β_. Thank you very much and look forward to your early reply.

**Comment by Albert0147** [comment]
Hi, I think we do not change k, for the decay factor we set it to 1, if I remembered correctly.
