### ISSUE TITLE
License of your code

### ISSUE THREAD

**Issue by Yu-Mitsuzumi** [Albert0147/LPA_SFDA#9]
Thank you for sharing your code!
I have a question about the license notation of your code. We are now planning to release our code that we created by referring to this code.  We would like to release our code while respecting your rights to this code, so if you don't mind, I would like you to specify how the code is licensed.

**Comment by Albert0147** [comment]
Hi,

Thanks for asking. The license will be CC BY 4.0.

Best regards

**Comment by Yu-Mitsuzumi** [comment]
Thank you for your quick reply!

I understand about the license. I would appreciate it very much if you could write about it in README.

Best regards
